import { Inter } from "next/font/google";
import "./globals.css";
import SecondaryBar from "@/components/shared/SecondaryBar";
import Footer from "@/components/shared/Footer";
import NavigationBar from "@/components/shared/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RTZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SecondaryBar></SecondaryBar>
        <NavigationBar></NavigationBar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
